server:
  port: 8080
spring:
  application:
    name: service-registry
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:8761/eureka
  instance:
    prefer-ip-address: true