services:

  discovery-service:
    container_name: discovery-service
    image: discovery-service
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - music-network

  gateway-service:
    container_name: gateway-service
    image: gateway-service
    build:
      context: ./gateway-service
    environment:
      DISCOVERY_SERVICE_HOST: ${DISCOVERY_SERVICE_HOST}
    ports:
      - "8080:8080"
    networks:
      - music-network
    depends_on:
      - discovery-service

  resources_db:
    container_name: resources_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - music-network

  songs_db:
    container_name: songs_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - music-network

  resource-service:
    container_name: resource-service
    image: resource-service
    build:
      context: ./resource-service
    environment:
      - "SPRING_PROFILES_ACTIVE=test"
    ports:
      - "8081:8081"
    networks:
      - music-network
    depends_on:
      - gateway-service
      - resources_db

  song-service:
#    container_name: song-service
    image: song-service
    build:
      context: ./song-service
#    environment:
#      SONGS_DB_HOST: songs_db
#      DISCOVERY_SERVICE_HOST: discovery-service
    ports:
      - "8082-8087:8082"
    networks:
      - music-network
    depends_on:
      - gateway-service
      - songs_db

volumes:
  postgres:

networks:
  music-network:
    driver: bridge