services:

  resources_db_postgres:
    container_name: resources_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - music-network

  songs_db_postgres:
    container_name: songs_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - music-network

  resource-service:
    container_name: resource-service
    image: resource-service
    environment:
      RESOURCES_DB_HOST: resources_db
      SONG_SERVICE_URL: http://song-service:8082/songs
    ports:
      - "8081:8081"
    networks:
      - music-network
    depends_on:
      - resources_db_postgres

  song-service:
    container_name: song-service
    image: song-service
    environment:
      SONGS_DB_HOST: songs_db
    ports:
      - "8082:8082"
    networks:
      - music-network
    depends_on:
      - songs_db_postgres

volumes:
  postgres:

networks:
  music-network:
    driver: bridge