spring:
  config:
    import: optional:classpath:.env.local[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka