server:
  port: 8081
spring:
  config:
    import: optional:classpath:.env.docker[.properties]
  datasource:
    url: jdbc:postgresql://${RESOURCES_DB_HOST}:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_HOST}:8761/eureka